      
    
 import java.awt.event.ActionEvent;
import java.sql.Connection;
 import java.sql.DriverManager;
 
 import java.sql.ResultSet;
 import java.sql.Statement;
 import java.util.ArrayList;

import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
 import javax.swing.table.TableModel;
import javax.swing.text.JTextComponent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
 public class Swing2 extends javax.swing.JFrame {
	 
		
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JTable jTable_Display_Users;
		private JTextComponent jTextField_Flight_Id;
		private JTextComponent jTextField_Flight_Name;
		private JTextComponent jTextField_Source;
		private JTextComponent jTextField_Destination;
		private JTextComponent jTextField_Departure;
		private JTextComponent jTextField_Arrived_Time;
		private JTextComponent jTextField_Flight_Class;
		private JTextComponent jTextField_Flight_Charges;
		private JTextComponent jTextField_Seats;
	
		
		
		
	 
     public Swing2() {
         initComponents();
         Show_Users_In_JTable();
     }
     
      // get the connection
    public Connection getConnection()
    {
        Connection con;
        try {
        	Class.forName("oracle.jdbc.driver.OracleDriver");
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","123");
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
         

  // get a list of users from mysql database
    public ArrayList<User1> getUsersList()
    {
        ArrayList<User1> usersList = new ArrayList<User1>();
        Connection connection = getConnection();
        
        String query = "SELECT * FROM  User1 ";
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            User1 user;
            while(rs.next())
            {
                user = new User1(rs.getString("Flight_Id"),rs.getString("Flight_Name"),rs.getString("Source"),rs.getString("Departure"),rs.getString("Destination"),rs.getString("Arrived_Time"),rs.getString("Flight_Class"),rs.getString("Flight_Charges"),rs.getString("Seats"));
                usersList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return usersList;
    }
   
 
    public void Show_Users_In_JTable()
    {
        ArrayList<User1> list = getUsersList();
        DefaultTableModel model = (DefaultTableModel)jTable_Display_Users.getModel();
        Object[] row = new Object[9];
        for(int i = 0; i<list.size(); i++)
        {
            row[0] = list.get(i).getFlight_id();       //.getFlight_ID();
            row[1] = list.get(i).getFlight_name();
            row[2] = list.get(i).getSource();
            row[3] = list.get(i).getDeparture();
            row[4] = list.get(i).getDestination();
            row[5] = list.get(i).getArrived_Time();
            row[6] = list.get(i).getFlight_class();
            row[7] = list.get(i).getFlight_charges();
            row[8] = list.get(i).getSeats();


            
            
            model.addRow(row);
        }
     }
         
    // Execute The Insert Update And Delete Querys
    public void executeSQlQuery(String query, String message)
    {
        Connection con = getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if((st.executeUpdate(query)) == 1)
            {
                // refresh jtable data
                DefaultTableModel model = (DefaultTableModel)jTable_Display_Users.getModel();
                model.setRowCount(0);
                Show_Users_In_JTable();
                
                JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
            }else{
                JOptionPane.showMessageDialog(null, "Data Not "+message);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
     private void initComponents() {

         jPanel1 = new javax.swing.JPanel();
         jScrollPane1 = new javax.swing.JScrollPane();
         jTable_Display_Users = new javax.swing.JTable();

         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

         jPanel1.setBackground(new java.awt.Color(204, 204, 204));
         jTable_Display_Users.setModel(new javax.swing.table.DefaultTableModel(
             new Object [][] {

             },
             new String [] {
                 "Flight_Id", "Flight_Name", "Source", "Departure","Destination","Arrived_Time","Flight_Class","Flight_Charges","Seats"
             }
         ));
         jTable_Display_Users.addMouseListener(new java.awt.event.MouseAdapter() {
             public void mouseClicked(java.awt.event.MouseEvent evt) {
                 jTable_Display_UsersMouseClicked(evt);
             }
         });
         jScrollPane1.setViewportView(jTable_Display_Users);

         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
         jPanel1Layout.setHorizontalGroup(
         	jPanel1Layout.createParallelGroup(Alignment.LEADING)
         		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
         			.addContainerGap(414, Short.MAX_VALUE)
         			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 409, GroupLayout.PREFERRED_SIZE)
         			.addContainerGap())
         );
         jPanel1Layout.setVerticalGroup(
         	jPanel1Layout.createParallelGroup(Alignment.LEADING)
         		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
         			.addContainerGap(-2147483648, Short.MAX_VALUE)
         			.addGap(18)
         			.addGap(18)
         			.addGap(18)
         			.addGap(18)
         			.addGap(192))
         		.addGroup(jPanel1Layout.createSequentialGroup()
         			.addContainerGap()
         			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
         			.addContainerGap(264, Short.MAX_VALUE))
         );
         jPanel1.setLayout(jPanel1Layout);
  
         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
         getContentPane().setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         );

         pack();
     }// </editor-fold>                        

     private void jButton_ExitActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		
	}

	private void jTextField_Flight_IDActionPerformed(java.awt.event.ActionEvent evt) {                                                     
         // TODO add your handling code here:
     }                                                    
     private void jTable_Display_UsersMouseClicked(java.awt.event.MouseEvent evt) {                                                  
         // Get The Index Of The Slected Row 
          int i = jTable_Display_Users.getSelectedRow();

          TableModel model = jTable_Display_Users.getModel();
          
           // Display Slected Row In JTexteFields
          jTextField_Flight_Id.setText(model.getValueAt(i,0).toString());
          jTextField_Flight_Name.setText(model.getValueAt(i,1).toString());
          jTextField_Source.setText(model.getValueAt(i,2).toString());
          jTextField_Departure.setText(model.getValueAt(i,3).toString());
          jTextField_Destination.setText(model.getValueAt(i,4).toString());
          jTextField_Arrived_Time.setText(model.getValueAt(i,5).toString());
          jTextField_Flight_Class.setText(model.getValueAt(i,6).toString());
          jTextField_Flight_Charges.setText(model.getValueAt(i,7).toString());
          jTextField_Seats.setText(model.getValueAt(i,8).toString());

      }                                                 
      // void jButton_ExitActionPerformed1(java.awt.event.ActionEvent evt) {
    	//  MenuTable mt= new MenuTable();
    	  //mt.setVisible(true);
    	  //dispose();
         
      //}//                                              


      //private MenuTable MenuTable() {
		// TODO Auto-generated method stub
		//return null;
	//}

	/**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
              for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                  if ("Nimbus".equals(info.getName())) {
                      javax.swing.UIManager.setLookAndFeel(info.getClassName());
                      break;
                  }
              }
          } catch (ClassNotFoundException ex) {
              java.util.logging.Logger.getLogger(Swing2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
              java.util.logging.Logger.getLogger(Swing2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
              java.util.logging.Logger.getLogger(Swing2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
              java.util.logging.Logger.getLogger(Swing2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
              public void run() {
                  new Swing2().setVisible(true);
              }
          });
      }
}

